name: 247 YouTube Live

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install gdown
        run: pipx install gdown

      - name: Download Video
        run: gdown 1cbTWtjuODy93JSZ8tqLLDa7n_janC6ym -O video.mp4

      - name: Start Streaming Loop
        run: |
          chmod +x stream.sh
          ./stream.sh
